using FitWifFrens.Data;
using FitWifFrens.Web.Telegram;
using Microsoft.ApplicationInsights;
using Microsoft.EntityFrameworkCore;

namespace FitWifFrens.Web.Background
{
    public class TelegramPollJobService
    {
        private const int TelegramPollOptionMaxLength = 100;

        private readonly DataContext _dataContext;
        private readonly TelegramBotService _telegramPollService;
        private readonly AiSummaryService _aiSummaryService;
        private readonly NotificationServiceConfiguration _notificationServiceConfiguration;
        private readonly TimeProvider _timeProvider;
        private readonly TelemetryClient _telemetryClient;
        private readonly ILogger<TelegramPollJobService> _logger;

        public TelegramPollJobService(
            DataContext dataContext,
            TelegramBotService telegramPollService,
            AiSummaryService aiSummaryService,
            NotificationServiceConfiguration notificationServiceConfiguration,
            TimeProvider timeProvider,
            TelemetryClient telemetryClient,
            ILogger<TelegramPollJobService> logger)
        {
            _dataContext = dataContext;
            _telegramPollService = telegramPollService;
            _aiSummaryService = aiSummaryService;
            _notificationServiceConfiguration = notificationServiceConfiguration;
            _timeProvider = timeProvider;
            _telemetryClient = telemetryClient;
            _logger = logger;
        }

        public async Task SendDailyCommitmentTelegramPolls(CancellationToken cancellationToken)
        {
            try
            {
                var today = DateOnly.FromDateTime(_timeProvider.GetUtcNow().UtcDateTime.ConvertTimeFromUtc());

                var commitments = await _dataContext.Commitments
                    .AsNoTracking()
                    .Include(c => c.TelegramPollRule).ThenInclude(r => r.Options)
                    .Where(c => c.TelegramPollRule != null)
                    .Where(c => c.Periods.Any(p => p.Status == CommitmentPeriodStatus.Current && p.StartDate <= today && today < p.EndDate))
                    .ToListAsync(cancellationToken);

                foreach (var commitment in commitments)
                {
                    var rule = commitment.TelegramPollRule!;
                    var options = await BuildPollOptionsAsync(rule, commitment.Id, cancellationToken);

                    var result = await _telegramPollService.SendPollAsync(
                        rule.Question,
                        options,
                        allowsMultipleAnswers: rule.AllowsMultipleAnswers,
                        isAnonymous: rule.IsAnonymous,
                        commitmentId: commitment.Id,
                        cancellationToken: cancellationToken);

                    _logger.LogInformation(
                        "Daily commitment poll sent. CommitmentId={CommitmentId}, PollId={PollId}, MessageId={MessageId}, ChatId={ChatId}",
                        commitment.Id,
                        result.PollId,
                        result.MessageId,
                        result.ChatId);
                }
            }
            catch (Exception exception)
            {
                _telemetryClient.TrackException(exception);
                throw;
            }
        }

        /// <summary>
        /// Builds the poll options to display. Each option keeps its meaning in parentheses
        /// exactly as stored — that parenthetical is what maps a vote back to its value (votes are
        /// scored by option index, and the meaning is the constant part) — but the funny label in
        /// front is regenerated by the AI each day. Falls back to the stored option text whenever
        /// the options don't follow the "funny label (meaning)" shape, don't fit Telegram's option
        /// length limit, or the AI doesn't return a clean label for every option.
        /// </summary>
        private async Task<string[]> BuildPollOptionsAsync(CommitmentTelegramPollRule rule, Guid commitmentId, CancellationToken cancellationToken)
        {
            var ordered = rule.Options.OrderBy(o => o.Index).ToList();
            var defaults = ordered.Select(o => o.Text).ToArray();

            try
            {
                var parsed = ordered.Select(o => SplitTrailingMeaning(o.Text)).ToList();

                // Only regenerate when every option has a trailing "(meaning)" to preserve.
                if (parsed.Any(p => p == null))
                {
                    return defaults;
                }

                var meanings = parsed.Select(p => p!.Value.Meaning).ToList();

                // Leave room for the " (meaning)" suffix within Telegram's option length limit.
                var maxLabelLength = TelegramPollOptionMaxLength - (meanings.Max(m => m.Length) + 3);
                if (maxLabelLength < 10)
                {
                    return defaults;
                }

                var context = await AiSummaryService.LoadChatContextAsync(_dataContext, _notificationServiceConfiguration.ChatId, cancellationToken);

                var labels = await _aiSummaryService.GeneratePollOptionLabels(
                    rule.Question,
                    meanings,
                    maxLabelLength,
                    cancellationToken,
                    context.AllUserFacts,
                    context.SoulPrompt,
                    context.MemorySummary);

                if (labels == null || labels.Count != ordered.Count)
                {
                    return defaults;
                }

                return ordered
                    .Select((o, i) =>
                    {
                        var built = $"{labels[i]} ({parsed[i]!.Value.Meaning})";
                        return built.Length <= TelegramPollOptionMaxLength ? built : o.Text;
                    })
                    .ToArray();
            }
            catch (Exception exception)
            {
                _logger.LogWarning(exception, "Failed to build dynamic poll options, using stored options. CommitmentId={CommitmentId}", commitmentId);
                return defaults;
            }
        }

        /// <summary>
        /// Splits a "funny label (meaning)" option into its funny prefix and the meaning inside
        /// the trailing parentheses. Returns null if the text does not end with a "(...)" group.
        /// </summary>
        private static (string Prefix, string Meaning)? SplitTrailingMeaning(string text)
        {
            var trimmed = text.TrimEnd();
            if (trimmed.Length == 0 || trimmed[^1] != ')')
            {
                return null;
            }

            var open = trimmed.LastIndexOf('(');
            if (open <= 0)
            {
                return null;
            }

            var meaning = trimmed.Substring(open + 1, trimmed.Length - 1 - (open + 1)).Trim();
            var prefix = trimmed[..open].Trim();
            if (meaning.Length == 0 || prefix.Length == 0)
            {
                return null;
            }

            return (prefix, meaning);
        }
    }
}
