// <auto-generated />
using System;
using FitWifFrens.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitWifFrens.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250519060340_AddingUserNickname")]
    partial class AddingUserNickname
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitWifFrens.Data.Commitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Commitments");
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentPeriod", b =>
                {
                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("CommitmentId", "StartDate", "EndDate");

                    b.ToTable("CommitmentPeriods");
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentPeriodUser", b =>
                {
                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<decimal>("Reward")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Stake")
                        .HasColumnType("numeric");

                    b.HasKey("CommitmentId", "StartDate", "EndDate", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommitmentPeriodUsers");
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentPeriodUserGoal", b =>
                {
                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("MetricName")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MetricType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderName")
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("CommitmentId", "StartDate", "EndDate", "UserId", "MetricName", "MetricType", "ProviderName");

                    b.HasIndex("MetricName", "ProviderName");

                    b.HasIndex("CommitmentId", "MetricName", "MetricType");

                    b.ToTable("CommitmentPeriodUserGoals");
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentUser", b =>
                {
                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<decimal>("Stake")
                        .HasColumnType("numeric");

                    b.HasKey("CommitmentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommitmentUsers");
                });

            modelBuilder.Entity("FitWifFrens.Data.Deposit", b =>
                {
                    b.Property<string>("Transaction")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Transaction");

                    b.HasIndex("UserId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("FitWifFrens.Data.Display", b =>
                {
                    b.Property<string>("MacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("character(17)")
                        .IsFixedLength();

                    b.HasKey("MacAddress");

                    b.ToTable("Displays");
                });

            modelBuilder.Entity("FitWifFrens.Data.Goal", b =>
                {
                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricName")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MetricType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("CommitmentId", "MetricName", "MetricType");

                    b.HasIndex("MetricName", "MetricType");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("FitWifFrens.Data.Metric", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Name");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("FitWifFrens.Data.MetricProvider", b =>
                {
                    b.Property<string>("MetricName")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderName")
                        .HasColumnType("character varying(256)");

                    b.HasKey("MetricName", "ProviderName");

                    b.HasIndex("ProviderName");

                    b.ToTable("MetricProviders");
                });

            modelBuilder.Entity("FitWifFrens.Data.MetricValue", b =>
                {
                    b.Property<string>("MetricName")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("MetricName", "Type");

                    b.ToTable("MetricValues");
                });

            modelBuilder.Entity("FitWifFrens.Data.Provider", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Name");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("FitWifFrens.Data.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FitWifFrens.Data.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("FitWifFrens.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FitWifFrens.Data.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("FitWifFrens.Data.UserDisplay", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("MacAddress")
                        .HasColumnType("character(17)");

                    b.HasKey("UserId", "MacAddress");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.ToTable("UserDisplays");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("FitWifFrens.Data.UserMetricProvider", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("MetricName")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("character varying(256)");

                    b.HasKey("UserId", "MetricName");

                    b.HasIndex("MetricName", "ProviderName");

                    b.ToTable("UserMetricProviders");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserMetricProviderValue", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("MetricName")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderName")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MetricType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("UserId", "MetricName", "ProviderName", "MetricType", "Time");

                    b.HasIndex("MetricName", "MetricType");

                    b.HasIndex("MetricName", "ProviderName");

                    b.ToTable("UserMetricProviderValues");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("FitWifFrens.Data.UserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentPeriod", b =>
                {
                    b.HasOne("FitWifFrens.Data.Commitment", "Commitment")
                        .WithMany("Periods")
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentPeriodUser", b =>
                {
                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("CommitmentPeriods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.CommitmentPeriod", "Commitment")
                        .WithMany("Users")
                        .HasForeignKey("CommitmentId", "StartDate", "EndDate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentPeriodUserGoal", b =>
                {
                    b.HasOne("FitWifFrens.Data.MetricProvider", "MetricProvider")
                        .WithMany("Goals")
                        .HasForeignKey("MetricName", "ProviderName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.Goal", "Goal")
                        .WithMany("Users")
                        .HasForeignKey("CommitmentId", "MetricName", "MetricType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.CommitmentPeriodUser", "User")
                        .WithMany("Goals")
                        .HasForeignKey("CommitmentId", "StartDate", "EndDate", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("MetricProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentUser", b =>
                {
                    b.HasOne("FitWifFrens.Data.Commitment", "Commitment")
                        .WithMany("Users")
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("Commitments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.Deposit", b =>
                {
                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("Deposits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.Goal", b =>
                {
                    b.HasOne("FitWifFrens.Data.Commitment", "Commitment")
                        .WithMany("Goals")
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.MetricValue", "MetricValue")
                        .WithMany("Goals")
                        .HasForeignKey("MetricName", "MetricType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");

                    b.Navigation("MetricValue");
                });

            modelBuilder.Entity("FitWifFrens.Data.MetricProvider", b =>
                {
                    b.HasOne("FitWifFrens.Data.Metric", "Metric")
                        .WithMany("Providers")
                        .HasForeignKey("MetricName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.Provider", "Provider")
                        .WithMany("Metrics")
                        .HasForeignKey("ProviderName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("FitWifFrens.Data.MetricValue", b =>
                {
                    b.HasOne("FitWifFrens.Data.Metric", "Metric")
                        .WithMany("Values")
                        .HasForeignKey("MetricName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("FitWifFrens.Data.RoleClaim", b =>
                {
                    b.HasOne("FitWifFrens.Data.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserClaim", b =>
                {
                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserDisplay", b =>
                {
                    b.HasOne("FitWifFrens.Data.Display", "Display")
                        .WithOne("User")
                        .HasForeignKey("FitWifFrens.Data.UserDisplay", "MacAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("Displays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Display");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserLogin", b =>
                {
                    b.HasOne("FitWifFrens.Data.Provider", "Provider")
                        .WithMany("Logins")
                        .HasForeignKey("LoginProvider")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserMetricProvider", b =>
                {
                    b.HasOne("FitWifFrens.Data.Metric", null)
                        .WithMany("Users")
                        .HasForeignKey("MetricName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("MetricProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.MetricProvider", "MetricProvider")
                        .WithMany("Users")
                        .HasForeignKey("MetricName", "ProviderName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserMetricProviderValue", b =>
                {
                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("MetricProviderValues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.MetricValue", "MetricValue")
                        .WithMany("Values")
                        .HasForeignKey("MetricName", "MetricType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.MetricProvider", "MetricProvider")
                        .WithMany("Values")
                        .HasForeignKey("MetricName", "ProviderName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricProvider");

                    b.Navigation("MetricValue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserRole", b =>
                {
                    b.HasOne("FitWifFrens.Data.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.UserToken", b =>
                {
                    b.HasOne("FitWifFrens.Data.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitWifFrens.Data.Commitment", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Periods");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentPeriod", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FitWifFrens.Data.CommitmentPeriodUser", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("FitWifFrens.Data.Display", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("FitWifFrens.Data.Goal", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FitWifFrens.Data.Metric", b =>
                {
                    b.Navigation("Providers");

                    b.Navigation("Users");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("FitWifFrens.Data.MetricProvider", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Users");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("FitWifFrens.Data.MetricValue", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("FitWifFrens.Data.Provider", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("FitWifFrens.Data.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FitWifFrens.Data.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("CommitmentPeriods");

                    b.Navigation("Commitments");

                    b.Navigation("Deposits");

                    b.Navigation("Displays");

                    b.Navigation("Logins");

                    b.Navigation("MetricProviderValues");

                    b.Navigation("MetricProviders");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
